### ISSUE TITLE
Encoding mismatch with other library

### ISSUE THREAD

**Issue by URockMan** [eerimoq/asn1tools#11]
ASN.1 specification:

Sorry for raising series of issues. 

The encoded reference value from playground link (whose value is same as our simulator value)and encoded value from this library are not matching. When i try to decode the encoded value from this library on below link it gives below response which is not the value which i have passed as input. 
Link : http://asn1-playground.oss.com/
**Encoded** Reference value from playbround link :6082F9E8A**906**A9169D4933A380

Input : {
             'aTCmessageheader':  {
                     'timestamp':  {
                              'timehours': 15, 
                              'timeminutes': 39, 
                              'timeseconds': 40
                      },
                     'msgreferencenumber': 1, 
                    'msgidentificationnumber': 1
               },
              'aTCuplinkmsgelementid':  {
                       'uM169Freetext': 'TESTING'
             }
}
UPER:
**Encoded**: 6082f9e8a**907**a9169d4933a380 (13 bytes)
Decoded using this library : {'aTCmessageheader': {'timestamp': {'timehours': 15, 'timeminutes': 39, 'timeseconds': 40}, 'msgreferencenumber': 1, 'msgidentificationnumber': 1}, 'aTCuplinkmsgelementid': {'uM169Freetext': u'TESTING'}}

Decoded value after passing encoded value from this library on playground link:
`rec1value ATCuplinkmessage ::= {
  aTCmessageheader {
    msgidentificationnumber 1,
    msgreferencenumber 1,
    timestamp {
      timehours 15,
      timeminutes 39,
      timeseconds 40
    }
  },
  aTCuplinkmsgelementid uM169Freetext : **{"TESTING",{0,0}}**
}`
Can you please help me in correcting the issue.

**Comment by URockMan** [comment]
I have tried using some generic example still both the encoded values are different using this library and asn1 play ground link.

ASN1 Structure:

```
Foo DEFINITIONS ::= BEGIN

    Question ::= SEQUENCE {
        id        INTEGER,
        question  Details
    }
	Details ::= CHOICE
	{
		name  [0] Freetext,
		place [1] Freetext
	}
	Freetext ::= IA5String (SIZE (1..256))
END
```
Input : question = {'id': 1, 'question': {'name':'TESTING'}}

Library encoded value : UPER:
Encoded: 010103d48b4ea499d1c0 (10 bytes)

ASN1 Playground link encoded value: 
Encoded: 010103548B4EA499D1C0

Please correct me if im using the library in wrong way.

**Comment by eerimoq** [comment]
Your usage is perfectly fine. The issue is that SIZE constrains are not implemented for UPER IA5String.

I implemented basic support for it in 0.36.0. Your example works with that version.

**Comment by URockMan** [comment]
Thanks for working on the fix. But I'm very sorry to say this i still see issues by trying different examples. Can you please check below examples where i can see additional **00** in the encoded string from library where i don't see them from asn1 playground link.

Question to encode: {'aTCmessageheader': {'timestamp': {'timehours': 12, 'timeminutes': 7, 'timeseconds': 50}, 'msgreferencenumber': 1, 'msgidentificationnumber': 1}, 'aTCuplinkmsgelementid': {'uM163ICAOfacilitydesignationTp4table': {'tp4table': 'labelA', 'iCAOfacilitydesignation': 'GDTA'}}}
Encoded Reference value from Airsim:6082F9E8A906A9169D4933A380

UPER:
Encoded: 
6082c1f2 a3**00**8f12 a410 (10 bytes)
6082C1F2 A3  8F12 A410 (ASN1 Play Ground)
Decoded: {'aTCmessageheader': {'timestamp': {'timehours': 12L, 'timeminutes': 7L, 'timeseconds': 50L}, 'msgreferencenumber': 1L, 'msgidentificationnumber': 1L}, 'aTCuplinkmsgelementid': {'uM163ICAOfacilitydesignationTp4table': {'tp4table': 'labelA', 'iCAOfacilitydesignation': u'GDTA'}}}


Question to encode: {'aTCmessageheader': {'timestamp': {'timehours': 12, 'timeminutes': 7, 'timeseconds': 50}, 'msgreferencenumber': 1, 'msgidentificationnumber': 1}, 'aTCuplinkmsgelementid': {'uM160ICAOfacilitydesignation': 'GDTA'}}

UPER:
Encoded: 
6082c1f2a**00**08f12a410 (10 bytes)
6082C1F2A  08F12A410 (ASN1 Play Ground)

Decoded: {'aTCmessageheader': {'timestamp': {'timehours': 12L, 'timeminutes': 7L, 'timeseconds': 50L}, 'msgreferencenumber': 1L, 'msgidentificationnumber': 1L}, 'aTCuplinkmsgelementid': {'uM160ICAOfacilitydesignation': u'GDTA'}}

**Comment by eerimoq** [comment]
Where can I find the ASN.1 specification? It's impossible to fix the issue without it.

**Comment by URockMan** [comment]
Shall I email it to you ?

**Comment by eerimoq** [comment]
Sure

**Comment by URockMan** [comment]
Sent please check.

**Comment by eerimoq** [comment]
Fixed in 0.37.0. Let me know if there are more issues. I know there are as constraints is not fully implemented.

**Comment by URockMan** [comment]
Thanks a lot. Will test now and update you the results.

**Comment by URockMan** [comment]
Thank you for the fix and updating the library. I have few more cases to execute. If i happen to find any issue will update in this thread.  

Thanks again for continuous support.

**Comment by URockMan** [comment]
If you look at why the decoded text is having trail character '**L**' appended to each value and also why the free text is having  " **u'** " every time. Will it be possible to remove those extra characters.

Decoded: {'aTCmessageheader': {'timestamp': {'timehours': 13L, 'timeminutes': 20L, 'timeseconds': 20L}, 'msgreferencenumber': 1L, 'msgidentificationnumber': 1L}, 'aTCuplinkmsgelementid': {'uM169Freetext': u'TESTING'}}

**Comment by eerimoq** [comment]
"L" means long integer and "u" unicode. They are standard Python types. It's unlikely that I will change the integer behavious, and strings are hard to handle correctly in a portable way. I think I'll stick to the current behaviour for now.

**Comment by eerimoq** [comment]
I found a few more problems with string encoding and decoding in the UPER codec. Part of release 0.38.0.
